version: '2'
services:
  app2automate-app:
    image: app2automate
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app2automate-postgresql:5432/app2automate
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://app2automate-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://app2automate-elasticsearch:9200
    ports:
      - 8080:8080
  app2automate-postgresql:
    extends:
      file: postgresql.yml
      service: app2automate-postgresql
  app2automate-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: app2automate-elasticsearch
